dailyfresh/apps/cart/urls.py
from django.conf.urls import url
from cart import views


urlpatterns = [
    # 添加购物车 : http://127.0.0.1:8000/cart/add
    url(r'^add$', views.AddCartView.as_view(), name='add'),

    # 购物车信息 : http://127.0.0.1:8000/cart/
    url(r'^$', views.CartInfoView.as_view(), name='info'),

    # 更新购物车 : http://127.0.0.1:8000/cart/update
    url(r'^update$', views.UpdateCartView.as_view(), name='update'),

    # 删除购物车 : http://127.0.0.1:8000/cart/delete
    url(r'^delete$', views.DeleteCartView.as_view(), name='delete')

]

dailyfresh/apps/goods/urls.py
from django.conf.urls import url
from goods import views


urlpatterns = [
    # 主页
    url(r'^index$', views.IndexView.as_view(), name='index'),
    # 详情页
    url(r'^detail/(?P<sku_id>\d+)$', views.DetailView.as_view(), name='detail'),
    # 列表页
    url(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)$', views.ListView.as_view(), name='list')

]

dailyfresh/apps/orders/urls.py
from django.conf.urls import url
from orders import views

urlpatterns = [
    # 订单确认
    url(r'^place$', views.PlaceOrderView.as_view(), name='place'),
    # 订单提交
    url(r'^commit$', views.CommitOrderView.as_view(), name='commit'),
    # 订单信息页面
    url(r'^(?P<page>\d+)$', views.UserOrdersView.as_view(), name='info'),
    # 订单支付
    url(r'^pay$', views.PayOrderView.as_view(), name='pay'),
    # 订单查询
    url(r'^checkpay$',views.CheckOrderView.as_view(), name='checkpay'),
    # 订单评论
    url(r'^comment/(?P<order_id>\d+)$', views.CommentOrderView.as_view(), name='comment')

]

dailyfresh/apps/users/urls.py
from django.conf.urls import  url
from apps.users import views

urlpatterns = [
    # url(r'^register$',views.register)
    url(r'^register$', views.RegisterView.as_view(),name='register'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^login$',views.LoginView.as_view(),name='login'),
    url(r'^address$',views.AddressView.as_view(),name='address'),
    url(r'^info$',views.UserInfoView.as_view(),name='info')
]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import haystack.urls
import tinymce.urls



urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/',include('users.urls',namespace='users')),

    url(r'^',include('goods.urls',namespace='goods')),
    url(r'^orders/',include('orders.urls',namespace='orders')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^cart/',include('cart.urls',namespace='cart'))
]

dailyfresh/apps/cart/models.py
from django.db import models

# Create your models here.

dailyfresh/apps/cart/views.py
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from goods.models import GoodsSKU
from django_redis import get_redis_connection
import json


# Create your views here.


class DeleteCartView(View):
    """删除购物车记录:一次删除一条"""

    def post(self, request):

        # 接收参数：sku_id
        sku_id = request.POST.get('sku_id')

        # 校验参数：not，判断是否为空
        if not sku_id:
            return JsonResponse({'code':1, 'message':'sku_id为空'})

        # 判断sku_id是否合法
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code':2, 'message':'要删除的商品不存在'})

        # 判断用户是否登录
        if request.user.is_authenticated():
            # 如果用户登陆，删除redis中购物车数据
            redis_conn = get_redis_connection('default')
            user_id = request.user.id
            redis_conn.hdel('cart_%s' % user_id, sku_id)

        else:
            # 如果用户未登陆，删除cookie中购物车数据
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                cart_dict = json.loads(cart_json)

                # 删除字典中某个key及对应的内容
                del cart_dict[sku_id]

                # 将最新的cart_dict,转成json字符串
                new_cart_json = json.dumps(cart_dict)

                # 删除结果写入cookie
                response = JsonResponse({'code': 0, 'message': '删除成功'})
                response.set_cookie('cart', new_cart_json)

                return response

        return JsonResponse({'code': 0, 'message': '删除成功'})


class UpdateCartView(View):
    """更新购物车信息"""

    def post(self, request):
        """+ - 手动输入"""

        # 获取参数：sku_id, count
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验参数all()
        if not all([sku_id, count]):
            return JsonResponse({'code': 1, 'message':'缺少参数'})

        # 判断商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code': 2, 'message': '商品不存在'})

        # 判断count是否是整数
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'code': 3, 'message': '商品数量错误'})

        # 判断库存
        if count > sku.stock:
            return JsonResponse({'code': 4, 'message': '库存不足'})

        # 判断用户是否登陆
        if request.user.is_authenticated():
            # 如果用户登陆，将修改的购物车数据存储到redis中
            redis_conn = get_redis_connection('default')
            user_id = request.user.id

            # 因为我们设计的接口是幂等的风格.传入的count就是用户最后要记录的商品的数量
            redis_conn.hset('cart_%s' % user_id, sku_id, count)

            return JsonResponse({'code': 0, 'message': '更新购物车成功'})
        else:
            # 如果用户未登陆，将修改的购物车数据存储到cookie中
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = {}

            # 因为我们设计的接口是幂等的风格.传入的count就是用户最后要记录的商品的数量
            cart_dict[sku_id] = count

            # 把cart_dict转成最新的json字符串
            new_cart_json = json.dumps(cart_dict)

            # 更新cookie中的购物车信息
            response = JsonResponse({'code': 0, 'message': '更新购物车成功'})
            response.set_cookie('cart', new_cart_json)

            return response


class CartInfoView(View):
    """购物车信息"""

    def get(self, request):
        """登录和未登录时查询购物车数据,并渲染"""

        if request.user.is_authenticated():
            # 用户已登录时,查询redis中购物车数据
            redis_conn = get_redis_connection('default')
            user_id = request.user.id
            # 如果字典是通过redis_conn.hgetall()得到的,那么字典的key和value信息都是bytes类型
            cart_dict = redis_conn.hgetall('cart_%s' % user_id)
        else:
            # 用户未登录时,查询cookie中的购物车数据
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                # 如果cart_dict字典从cookie中得到的,那么key是字符串,value是int
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = {}

        # 定义临时变量
        skus = []
        total_count = 0
        total_sku_amount = 0

        # cart_dict = {sku_id1:count1, sku_id2:count2}
        for sku_id, count in cart_dict.items():

            try:
                sku = GoodsSKU.objects.get(id=sku_id)
            except GoodsSKU.DoesNotExist:
                continue # 有异常,跳过.展示没有异常的数据

            #  统一count的数据类型为int,方便后续代码的计算和比较
            count = int(count)
            # 小计
            amount = count * sku.price

            # 提示:python是动态的面向对象的语言,所以可以动态的给sku对象添加属性,存储count和amount
            sku.count = count
            sku.amount = amount
            # 记录sku
            skus.append(sku)

            # 总金额和总计
            total_sku_amount += amount
            total_count += count

        # 构造上下文
        context = {
            'skus':skus,
            'total_sku_amount':total_sku_amount,
            'total_count':total_count
        }

        # 渲染模板
        return render(request, 'cart.html', context)


class AddCartView(View):
    """添加到购物车"""

    def post(self, request):
        """接受购物车参数,校验购物车参数,保存购物车参数"""

        # 判断用户是否登录
        # if not request.user.is_authenticated():
        #     return JsonResponse({'code':1, 'message':'用户未登录'})

        # 接受购物车参数 : sku_id, count
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 校验参数 : all()
        if not all([sku_id, count]):
            return JsonResponse({'code':2, 'message':'缺少参数'})

        # 判断sku_id是否合法
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'code':3, 'message': '商品不存在'})

        # 判断count是否合法
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'code':4, 'message': '商品数量错误'})

        # 判断库存是否超出
        if count > sku.stock:
            return JsonResponse({'code':5, 'message': '库存不足'})

        if request.user.is_authenticated():

            # 获取user_id
            user_id = request.user.id

            # 保存购物车数据到Redis
            redis_conn = get_redis_connection('default')
            # 需要查询要保存到购物车的商品数据是否存在,如果存在,需要累加,反之,赋新值
            origin_count = redis_conn.hget('cart_%s' % user_id, sku_id)
            if origin_count is not None:
                count += int(origin_count) # django_redis保存的hash类型的数据是bytes类型的

            # 再次:判断库存是否超出,拿着最终的结果和库存比较
            if count > sku.stock:
                return JsonResponse({'code': 5, 'message': '库存不足'})

            redis_conn.hset('cart_%s' % user_id, sku_id, count)

            # 查询购物车中的商品数量,响应给前端
            cart_num = 0
            cart_dict = redis_conn.hgetall('cart_%s' % user_id)
            for val in cart_dict.values():
                cart_num += int(val)

            # 响应结果
            return JsonResponse({'code':0, 'message': '添加购物车成功', 'cart_num':cart_num})
        else:
            # 用户未登录,保存购物车数据到cookie {sku_id:count}
            # 读取cookie中的购物车数据
            cart_json = request.COOKIES.get('cart')
            if cart_json is not None:
                # 把cart_json转成字典 : loads 将json字符串转成json字典
                cart_dict = json.loads(cart_json)
            else:
                cart_dict = {} # 为了后面继续很方便的操作购物车数据,这里定义空的字典对象

            # 判断要存储的商品信息,是否已经存在.如果已经存在就累加.反之,赋新值
            # 提醒 : 需要保证 sku_id和cart_dict里面的key的类型一致;此处的正好一致
            if sku_id in cart_dict:
                origin_count = cart_dict[sku_id] # origin_count : 在json模块中,数据类型不变
                count += origin_count

            # 再再次:判断库存是否超出,拿着最终的结果和库存比较
            if count > sku.stock:
                return JsonResponse({'code': 5, 'message': '库存不足'})

            # 把最新的商品的数量,赋值保存到购物车字典
            cart_dict[sku_id] = count

            # 在写入cookie之前,将cart_dict转成json字符串
            new_cart_json = json.dumps(cart_dict)

            # 为了方便前端展示最新的购物车数量,后端添加购物车成功后,需要查询购物车
            cart_num = 0
            for val in cart_dict.values():
                cart_num += val # val 是json模块运作的,存储的市数字,读取的也是数字

            # 创建response
            response = JsonResponse({'code':0, 'message':'添加购物车成功', 'cart_num':cart_num})

            # 写入cookie
            response.set_cookie('cart', new_cart_json)

            return response

dailyfresh/templates/list.html
{% extends 'base.html' %}


{% block title %}
天天生鲜-商品列表
{% endblock title %}


{% block body %}


	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">

                    {% for category in categorys %}
                        <li><a href="{% url 'goods:list' category.id 1 %}" class="{{ category.logo }}">{{ category.name }}</a></li>
                    {% endfor %}

				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="#">{{ category.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>

                    {% for new_sku in new_skus %}
                        <li>
                            <a href="{% url 'goods:detail' new_sku.id %}"><img src="{{ new_sku.default_image.url }}"></a>
                            <h4><a href="{% url 'goods:detail' new_sku.id %}">{{ new_sku.name }}</a></h4>
                            <div class="prize">￥{{ new_sku.price }}</div>
					    </li>
                    {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
                {# http://127.0.0.1:8000/list/1/1?sort=default #}
				<a href="{% url 'goods:list' category.id 1 %}?sort=default" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' category.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' category.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">

                {% for page_sku in page_skus %}
                    <li>
                        <a href="{% url 'goods:detail' page_sku.id %}"><img src="{{ page_sku.default_image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' page_sku.id %}">{{ page_sku.name }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ page_sku.price }}</span>
                            <span class="unit">{{ page_sku.price }}/{{ page_sku.unit }}</span>
                            <a href="#" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                {% endfor %}

			</ul>

			<div class="pagenation">

                {% if page_skus.has_previous  %}
                    <a href="{% url 'goods:list' category.id page_skus.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}

				{% for index in page_list %}
                    <a href="{% url 'goods:list' category.id index %}?sort={{ sort }}" {% if index == page_skus.number %}class="active"{% endif %}>{{ index }}</a>
				{% endfor %}

                {% if page_skus.has_next %}
                    <a href="{% url 'goods:list' category.id page_skus.next_page_number %}?sort={{ sort }}">下一页</a>
                {% endif %}

			</div>
		</div>
	</div>

{% endblock body %}

dailyfresh/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>

    {% load staticfiles %}

    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post">

                        {% csrf_token %}

						<input type="text" name="user_name" class="name_input" placeholder="请输入用户名">
{#						<div class="user_error">输入错误</div>#}
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
{#						<div class="pwd_error">输入错误</div>#}
						<div class="more_input clearfix">
							<input type="checkbox" name="remembered">
							<label>记住用户名</label>
						</div>
                        <div>{{ error }}</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

dailyfresh/templates/order_comment.html
{% extends 'user_center_base.html' %}

{% load staticfiles %}

{% block title %}天天生鲜-用户中心{% endblock %}

{% block body %}
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
				<li><a href="{% url 'users:info' %}">· 个人信息</a></li>
				<li><a href="{% url 'orders:info' 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}">· 收货地址</a></li>
			</ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">订单评价</h3>
                <ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.create_time}}</li>
					<li class="col02">订单号：{{order.order_id}}</li>
					<li class="col02 stress">{{order.status_name}}</li>
				</ul>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="order_id" value="{{order.order_id}}">
                <input type="hidden" name="total_count" value="{{order.skus|length}}">
                {% for sku in order.skus %}
                <table class="order_list_table w980">
                    <tbody>
                        <tr>
                            <td width="80%">
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{{ sku.default_image.url }}"></li>
                                    <li class="col02">{{sku.name}}<em>{{sku.price}}/{{sku.unit}}</em></li>
                                    <li class="col03">{{sku.count}}</li>
                                </ul>
                            </td>
                            <td width="20%">{{sku.amount}}元</td>
                        </tr>
                    </tbody>
                </table>
                <div class="site_con">
                    <input type="hidden" name="sku_{{forloop.counter}}" value="{{sku.id}}">
                    <div class="form_group form_group2">
                        <label>评价内容：</label>
                        <textarea class="site_area" name="content_{{forloop.counter}}"></textarea>
                    </div>
                </div>
                {% endfor %}
                <input type="submit" name="" value="提交" class="info_submit">
            </form>
        </div>
    </div>
{% endblock %}

dailyfresh/templates/static_base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

{% load staticfiles %}

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {% endblock topfiles %}
</head>

<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">

				<div class="login_btn fl">
					<a href="{% url 'users:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>

				<div class="user_link fl">
					<span>|</span>
					<a href="#">用户中心</a>
					<span>|</span>
					<a href="#">我的购物车</a>
					<span>|</span>
					<a href="#">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

    {% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_num }}</div>
		</div>
	</div>
    {% endblock search_bar %}

    {% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    {% block footer %}{% endblock footer %}

    {% block bottom_files %}{% endblock bottom_files %}

</body>
</html>

dailyfresh/templates/user_center_info.html
{% extends 'user_center_base.html' %}


{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:info' %}" class="active">· 个人信息</a></li>
				<li><a href="user_center_order.html">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							<li><span>联系方式：</span>{{ address.receiver_mobile }}</li>
							<li><span>联系地址：</span>{{ address.detail_addr }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">

                        {% for sku in sku_list %}
                            <li>
                                <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.default_image.url }}"></a>
                                <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                                <div class="operate">
                                    <span class="prize">￥{{ sku.price }}</span>
                                    <span class="unit">{{ sku.price }}/{{ sku.unit }}</span>
                                    <a href="#" class="add_goods" title="加入购物车"></a>
                                </div>
                            </li>
                        {% endfor %}

			        </ul>
		</div>
		</div>
	</div>

{% endblock body %}

dailyfresh/templates/user_center_order.html
{% extends 'user_center_base.html' %}

{% load staticfiles %}

{% block title %}天天生鲜-用户中心{% endblock %}

{% block body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'users:info' %}">· 个人信息</a></li>
				<li><a href="{% url 'orders:info' 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'users:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				{% for order in orders %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.create_time}}</li>
					<li class="col02">订单号：{{order.order_id}}</li>
					<li class="col02 stress">{{order.status_name}}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{% for sku in order.skus %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{{sku.default_image.url}}"></li>
									<li class="col02">{{sku.name}}<em>{{sku.price}}/{{sku.unit}}</em></li>
									<li class="col03">{{sku.count}}</li>
									<li class="col04">{{sku.amount}}元</li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{order.total_amount}}元<br/>（含运费{{order.trans_cost}}元）</td>
							<td width="15%">{{order.pay_method_name}}</td>
							<td width="15%"><a href="javascript:;" order_id="{{order.order_id}}" order_status="{{order.status}}" class="oper_btn">
                                {{ order.status_name }}
							</a></td>
						</tr>
					</tbody>
				</table>
				{% endfor %}

				<div class="pagenation">
				{% if orders.has_previous %}
					<a href="{% url 'orders:info' orders.previous_page_number %}">上一页</a>
				{% endif %}
				{% for p in page_list %}
					<a href="{% url 'orders:info' p %}" {% if p == order.number %}class="active"{% endif %}>{{p}}</a>
				{% endfor %}
				{% if orders.has_next %}
					<a href="{% url 'orders:info' orders.next_page_number %}">下一页></a>
				{% endif %}
				</div>
		</div>
	</div>
{% endblock %}

{% block bottom_files %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$('.oper_btn').click(function() {
			var order_id = $(this).attr("order_id");
			var order_status = $(this).attr("order_status");
			order_status = parseInt(order_status);
			if (1 == order_status) {
			    // 表示订单待支付，向django后端索要支付宝的支付链接
				var req_data = {
				    order_id: order_id,
					csrfmiddlewaretoken: "{{ csrf_token }}"
				};
				$.post('/orders/pay', req_data, function(data){
                    if ( 1 == data.code ) {
                        // 用户未登录
                        location.href = "/users/login";
                    } else if (0 == data.code ) {
                        // 成功拿到了支付连接，开启一个新页面，让用户在新页面进行支付
                        window.open(data.url);

                        $.get("/orders/checkpay?order_id="+order_id, function (resp_data) {
                            if (0 == resp_data.code) {
                                // 支付成功
								alert("支付成功");
                                location.reload();
                            } else {
                                alert(resp_data.message);
                            }
                        });
                    } else {
                        alert(data.message);
                    }
				});
			} else if (4 == order_status) {
			    // window.location.href = ("/orders/comment/" + order_id);
{#				location.href = ("/orders/comment/" + order_id);#}
			} 
		});
	</script>
{% endblock %}